### ISSUE TITLE
Unable to run sushi

### ISSUE THREAD

**Issue by OxeStone** [kura52/sushi-browser#61]
When I run sushi from the command line I get the message below. Both sush and Chrome open and show a blank page. Nothing else happens. Any suggestion?
 (node:7128) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Trace: uncaughtException TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Function.getFocusedWindow (D:\Software\_PortableApps\sushi-browser-portable\resources\app.asar\lib\remoted-chrome\Browser.js:977:39)
    at getCurrentWindow (D:\Software\_PortableApps\sushi-browser-portable\resources\app.asar\lib\util.js:15:34)
    at portableResourcePathSelector (D:\Software\_PortableApps\sushi-browser-portable\resources\app.asar\lib\portablePathSelector.js:14:41)
    at Timeout._onTimeout (D:\Software\_PortableApps\sushi-browser-portable\resources\app.asar\lib\portablePathSelector.js:31:19)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
    at Object.trace (internal/console/constructor.js:338:11)
    at process.<anonymous> (D:\Software\_PortableApps\sushi-browser-portable\resources\app.asar\lib\main.js:21:11)
    at process.emit (events.js:199:15)
    at process._fatalException (internal/process/execution.js:141:25)

**Comment by OxeStone** [comment]
Update: If scaling under 'Settings' > 'Change the size of text, apps, and other items' is anything other than 100% sushi displays a blank page. Please fix.

**Comment by kura52** [comment]
Thank you for raising this issue.
I fixed it in v0.25.0.
